- block:
    - name: uploading command file
      copy:
        src: consul
        dest: /usr/bin/
        mode: 755
  rescue:
    - name: downloading consul
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ version }}/consul_{{ version }}_linux_amd64.zip"
        dest: roles/deploy.Consul/files/
        remote_src: yes
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: install.yml
  always:
    - name: creating user 'consul'
      user:
        name: consul
    - name: creating /etc/consul.d
      file:
        path: "/etc/consul.d/{{ item }}"
        state: directory
      with_items:
        - bootstrap
        - server
        - client
    - name: creating /var/consul
      file:
        path: /var/consul
        state: directory
        owner: consul
        group: consul
    - name: bootstrap the cluster
      include_tasks: bootstrap.yml
