- block:
    - name: uploading command file
      copy:
        src: downloaded_files/consul
        dest: /usr/local/bin/consul
        mode: 0755
  rescue:
    - name: downloading consul
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: downloaded_files/
        remote_src: yes
      register: download
      until: download|succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: install.yml
  always:
    - name: creating user 'consul'
      user:
        name: consul
    - name: creating /etc/consul.d
      file:
        path: /etc/consul.d/
        state: directory
        owner: consul
        group: consul
    - name: creating /var/consul
      file:
        path: /var/consul
        state: directory
        owner: consul
        group: consul
    - name: enable DNS port forwarding
      command: '{{ item }}'
      with_items:
        - iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
