- name: updating /etc/resolvconf/resolv.conf.d/base
  template:
    src: consul_dns.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  notify: Restart resolvconf service
  when: ansible_os_family == 'Debian'

- name: updating /etc/resolv.conf
  template:
    src: consul_dns.j2
    dest: /etc/resolv.conf
  when: ansible_os_family == 'RedHat'
