- include_vars:
    file: key.yml

- name: stop and remove consul-client service
  service:
    name: consul-client
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: updating server config
  template:
    src: 'config.json.j2'
    dest: '/etc/consul.d/server/config.json'
  register: config

- name: updating services config
  template:
    src: '{{ item }}.json.j2'
    dest: '/etc/consul.d/server/{{ item }}.json'
  when: "item in group_names"
  with_items:
    - elastic
    - logstash
    - kibana
  register: services

- name: validate config
  command: consul validate -quiet /etc/consul.d/server/
  when: config.changed or services.changed
  notify: Restart consul server
