- include_vars:
    file: key.yml

- name: stop and remove consul-client service
  service:
    name: consul-client
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: updating config
  block:
    - template:
        src: server_config.json.j2
        dest: /etc/consul.d/server/config.json
    - template:
        src: 'service_{{ item }}.json.j2'
        dest: '/etc/consul.d/server/{{ item }}.json'
      when: "item in group_names"
      with_items:
        - elastic
        - logstash
        - kibana
      register: config

- name: testing config
  command: consul validate /etc/consul.d/server
  notify: Restart consul server
  when: config.changed
