- name: config /usr/lib/systemd/system/elasticsearch.service
  ini_file:
    path: /usr/lib/systemd/system/elasticsearch.service
    section: Service
    option: LimitMEMLOCK
    value: infinity

- name: updating ElasticSearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: starting ElasticSearch service
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: started

- wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 9200
