- name: config /usr/lib/systemd/system/elasticsearch.service
  ini_file:
    path: /usr/lib/systemd/system/elasticsearch.service
    section: Service
    option: LimitMEMLOCK
    value: infinity

- name: updating ElasticSearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- include_tasks: "plugins.yml target={{ target }}"
  with_items:
    - ingest-geoip
    - ingest-user-agent
  loop_control:
    loop_var: target

- name: starting ElasticSearch service
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: started

- wait_for:
    host: '{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}'
    port: 9200
