- block:
    - name: 'uploading elasticsearch-{{ elk_version }}.deb'
      copy:
        src: 'downloaded_files/elasticsearch-{{ elk_version }}.deb'
        dest: /tmp/
    - name: 'installing elasticsearch-{{ elk_version }}.deb'
      apt:
        deb: '/tmp/elasticsearch-{{ elk_version }}.deb'
    - name: starting elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes
        daemon_reload: yes
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: 'removing /tmp/elasticsearch-{{ elk_version }}.deb'
      file:
        path: '/tmp/elasticsearch-{{ elk_version }}.deb'
        state: absent

- include_tasks: common_setup.yml
