- block:
    - name: 'checking elasticsearch-{{ elk_version }}.deb file'
      stat:
        path: "roles/deploy.ElasticSearch/files/elasticsearch-{{ elk_version }}.deb"
        get_attributes: no
        get_checksum: no
        get_md5: no
        get_mime: no
      register: fileSt
      failed_when: not fileSt.stat.exists
      delegate_to: localhost
      become: no
      run_once: yes
  rescue:
    - name: 'downloading elasticsearch-{{ elk_version }}.deb'
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_version }}.deb"
        dest: "roles/deploy.ElasticSearch/files/elasticsearch-{{ elk_version }}.deb"
      delegate_to: localhost
      become: no
      run_once: yes

- name: 'uploading elasticsearch-{{ elk_version }}.deb'
  copy:
    src: 'elasticsearch-{{ elk_version }}.deb'
    dest: /tmp/

- name: 'installing elasticsearch-{{ elk_version }}.deb'
  apt:
    deb: '/tmp/elasticsearch-{{ elk_version }}.deb'

- include_tasks: common_setup.yml
