- block:
    - name: 'uploading elasticsearch-{{ elk_version }}.deb'
      copy:
        src: 'downloaded_files/elasticsearch-{{ elk_version }}.deb'
        dest: /tmp/
    - name: 'installing elasticsearch-{{ elk_version }}.deb'
      apt:
        deb: '/tmp/elasticsearch-{{ elk_version }}.deb'
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'

- include_tasks: common_setup.yml
