- block:
    - name: 检查 ElasticSearch 进程是否存在
      shell: ps xua | grep -v grep | grep -i elasticsearch
      changed_when: false
  rescue:
    - include_tasks: env_check.yml
    - include_tasks: '{{ ansible_os_family }}.yml'

- name: 更新 ElasticSearch 相关配置文件
  template:
    src: '{{ item }}.j2'
    dest: '/etc/elasticsearch/{{ item }}'
  with_items:
    - jvm.options
    - elasticsearch.yml
  register: configSt

- name: 重启 ElasticSearch 服务
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: yes
  when:
    - configSt|changed

- wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: '{{ item }}'
  with_items:
    - 9300
    - 9200

- block:
    - name: 检查 ElasticSearch 版本
      uri:
        url: 'http://{{ ansible_default_ipv4.address }}:9200'
        return_content: yes
      register: versionCheck
      changed_when: false
      failed_when: elk_version > versionCheck.json.version.number
  rescue:
    - include_tasks: pre_upgrade.yml
    - include_tasks: '{{ ansible_os_family }}.yml'
    - include_tasks: post_upgrade.yml
