- name: '检查 {{ elastic_http_new_port }} 端口是否全局可用'
  wait_for:
    host: '{{ item }}'
    port: '{{ elastic_http_new_port }}'
    state: stopped
    timeout: 3
  with_items:
    - 127.0.0.1
    - '{{ ansible_all_ipv4_addresses }}'
  when: "elastic_http_port != elastic_http_new_port"
  register: portSt

- name: '写入本地全局变量文件 group_vars/all.yml'
  run_once: true
  lineinfile:
    path: group_vars/all.yml
    regexp: '^elastic_http_port'
    line: 'elastic_http_port: {{ elastic_http_new_port }}'
  when: portSt|succeeded
  delegate_to: localhost
  become: no
