- name: checking cluster health status
  uri:
    url: http://{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:{{ elastic_http_port }}/_cluster/health
    method: GET
    return_content: yes
    body_format: json
  register: health

- fail:
    msg: "Current cluster status is not 'green', please fix it before upgrade."
  when: health.json.status != "green"

- name: stopping shards
  uri:
    url: "http://{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:{{ elastic_http_port }}/_cluster/settings"
    method: PUT
    body: "{{ lookup('file','disable_shard.json') }}"
    body_format: json

- name: stopping service
  service:
    name: elasticsearch
    state: stopped

- name: waiting for port down
  wait_for:
    host: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
    port: '{{ elastic_http_port }}'
    state: stopped
