- block:
    - name: 'uploading elasticsearch-{{ elk_version }}.rpm'
      copy:
        src: 'downloaded_files/elasticsearch-{{ elk_version }}.rpm'
        dest: /tmp/
    - name: 'installing elasticsearch-{{ elk_version }}.rpm'
      yum:
        name: '/tmp/elasticsearch-{{ elk_version }}.rpm'
        state: present
  rescue:
    - name: 'downloading elasticsearch-{{ elk_version }}.rpm'
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_version }}.rpm"
        dest: "downloaded_files/elasticsearch-{{ elk_version }}.deb"
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: '{{ ansible_os_family }}.yml'

- include_tasks: common_setup.yml
