- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - include_role:
        name: init
        tasks_from: check_python.yml
    - setup:
  roles:
    - init
  post_tasks:
    - pause:
        prompt: |
          You should reboot the systems
          before next move if they are new.
