- hosts: all
  become: yes
  gather_facts: no
  vars:
    check_groups: true
  pre_tasks:
    - include_role:
        name: init
        tasks_from: check_python.yml
  roles:
    - init
    - deploy.Chrony
