- hosts: all
  become: yes
  serial:
    - 1
    - 30%
  gather_facts: no
  vars:
    check_groups: true
  pre_tasks:
    - include_role:
        name: init
        tasks_from: check_python.yml
    - setup:
  roles:
    - init
