- hosts: all
  become: yes
  serial:
    - 1
    - 30%
  vars_prompt:
    - name: "bootstrap"
      prompt: "First time to deploy?(y/N)"
      default: 'N'
      private: no
    - name: "datacenter_name"
      prompt: "What is the consul datacenter name?"
      default: "elk"
      private: no
  roles:
    - deploy.Consul
