- hosts: all
  tasks: []
  
- hosts: all
  become: yes
  serial:
    - 1
    - 30%
  roles:
    - deploy.Consul
  post_tasks:
    - block:
        - name: waiting for service started
          wait_for:
            port: 8600
            timeout: 30
      rescue:
        - service:
            name: consul
            state: restarted
        - wait_for:
            port: 8600
            timeout: 30
