- hosts: all
  become: yes
  serial:
    - 1
    - 30%
  vars_prompt:
    - name: "bootstrap"
      prompt: "Bootstrap a consul cluster?(y/N)"
      default: 'N'
      private: no
  roles:
    - deploy.Consul
  post_tasks:
    - block:
        - wait_for:
            port: 8600
            timeout: 30
      rescue:
        - service:
            name: consul
            state: restarted
        - wait_for:
            port: 8600
            timeout: 30
