- hosts: elasticsearch
  become: yes
  serial:
    - 1
    - 10%
  roles:
    - deploy.ElasticSearch
    - deploy.Consul
    - deploy.Monit
  post_tasks:
    - block:
        - wait_for:
            port: '{{ elastic_http_port }}'
            timeout: 60
      rescue:
        - service:
            name: elasticsearch
            state: restarted
        - wait_for:
            port: '{{ elastic_http_port }}'
            timeout: 120
