- hosts: kibana
  become: yes
  serial:
    - 1
    - 10
  roles:
    - deploy.Kibana
    - deploy.Consul
    - deploy.Monit
  post_tasks:
    - block:
        - wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
      rescue:
        - service:
            name: kibana
            state: started
            enabled: yes
        - wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
