- hosts: logstash
  become: yes
  serial:
    - 1
    - 10%
  roles:
    - deploy.Consul
    - deploy.Logstash
    - deploy.Monit
  post_tasks:
    - block:
        - name: waiting for service started
          wait_for:
            port: '{{ logstash_beats_port }}'
            timeout: 120
      rescue:
        - service:
            name: logstash
            state: restarted
        - wait_for:
            port: '{{ logstash_beats_port }}'
            timeout: 120
