- hosts: all
  become: yes
  roles:
    - {
      role: deploy.Beats,
      target: filebeat,
      tags: filebeat
    }
    - {
      role: deploy.Beats,
      target: metricbeat,
      tags: metricbeat
    }
