- name: restart redis-sentinel
  service:
    name: redis-sentinel
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart redis-server
  service:
    name: redis-server
    state: restarted
    daemon_reload: yes
    enabled: yes
