- name: unarchive files
  unarchive:
    src: downloaded_files/redis-stable.tar.gz
    dest: /tmp/
  delegate_to: localhost
  run_once: yes
  become: no

- name: compling...
  command: make
  args:
    chdir: /tmp/redis-stable
  delegate_to: localhost
  run_once: yes
  become: no

- name: testing...
  command: make
  args:
    chdir: /tmp/redis-stable
  delegate_to: localhost
  run_once: yes
  become: no

- name: copying files
  copy:
    src: "/tmp/redis-stable/src/redis-{{ item }}"
    dest: "roles/deploy.Redis/files/redis-{{ item }}"
  with_items:
    - cli
    - sentinel
    - server
  delegate_to: localhost
  run_once: yes
  become: no
