- name: creating user 'redis'
  user:
    name: redis
    system: yes
    create_home: no

- block:
    - name: uploading redis binary files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}{{ item.src }}"
        mode: 0555
      with_items:
        - src: redis-cli
          dest: /usr/bin/
        - src: redis-server
          dest: /usr/sbin/
        - src: redis-sentinel
          dest: /usr/sbin/
  rescue:
    - include_tasks: download.yml
    - include_tasks: build.yml
    - include_tasks: install.yml
  always:
    - name: creating directories
      file:
        path: "{{ item }}"
        state: directory
        owner: redis
        group: redis
        mode: 0770
      with_items:
        - /etc/redis
        - /var/lib/redis
        - /var/log/redis
    - name: Config limit.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: '{{ item }}'
      with_items:
        - 'ulimit -n 65536'
        - 'fsize unlimited'
