- block:
    - name: checking redis command
      command: test -e /usr/sbin/redis-server
      changed_when: false
  rescue:
    - include_tasks: install.yml
    - include_tasks: system_config.yml

- include_tasks: service_config.yml

- name: coping check_redis_master.sh script
  copy:
    src: check_redis_master.sh
    dest: /usr/local/bin/check_redis_master.sh
    mode: 0755
