- name: restarting redis-sentinel
  service:
    name: redis-sentinel
    state: restarted
    daemon_reload: yes
    enabled: yes

- wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + bond_interface]['ipv4']['address'] }}"
    port: 26379
    timeout: 120
