- name: updating redis.conf
  template:
    src: "redis.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: redis
    group: root
    mode: 0660
  register: serverConfig
  notify: restart redis-server

# - include_tasks: restart_redis.yml
#   when: serverConfig is changed

- name: updating sentinel.conf
  lineinfile:
    path: /etc/redis/sentinel.conf
    create: yes
    owner: redis
    group: root
    mode: 0660
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - line: "bind {{ hostvars[inventory_hostname]['ansible_' + bond_interface]['ipv4']['address'] }}"
      regexp: "^bind"
    - line: "port 26379"
      regexp: "^port"
    - line: "sentinel monitor {{ groups['redis'][0] }} {{ hostvars[groups['redis'][0]]['ansible_' + bond_interface]['ipv4']['address'] }} 6379 2"
      regexp: "^sentinel monitor"
    - line: "sentinel down-after-milliseconds {{ groups['redis'][0] }} 10000"
      regexp: "^sentinel down-after-milliseconds"
    - line: "sentinel parallel-syncs {{ groups['redis'][0] }} 1"
      regexp: "^sentinel parallel-syncs"
    - line: "sentinel failover-timeout {{ groups['redis'][0] }} 300000"
      regexp: "^sentinel failover-timeout"
  register: sentinelConfig
  notify: restart redis-sentinel

# - include_tasks: restart_sentinel.yml
#   when: sentinelConfig is changed
