- name: Restart consul service
  service:
    name: consul
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart resolvconf service
  service:
    name: resolvconf
    state: restarted
  when: ansible_os_family == 'Debian'
