- name: Update monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    mode: 0700
    owner: root
    group: root

- name: Install/update config for all
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0700
  with_items:
    - check_fs_usage
    - check_sysload
    - check_services

- name: Install/update config on elastic master nodes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  when: "'elasticMasterNode' in group_names"
  with_items:
    - check_hosts

- include_tasks: config_test.yml
