- name: Test monit config
  command: /usr/local/bin/monit -t
  register: monitTest

- block:
    - name: Reload monit
      service:
        name: monit
        state: reloaded
      when: monitTest is succeeded
  rescue:
    - name: Start monit
      service:
        name: monit
        state: started
        enabled: true
        daemon_reload: yes
