- name: Update monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    mode: 0600
    owner: root
    group: root

- name: Install/update config for all
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  with_items:
    - check_fs_usage
    - check_sysload
    - check_services
  register: configAll

- name: Install/update config on elastic master nodes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  with_items:
    - check_hosts
  register: configEsMaster

- include_tasks: config_test.yml
  when: (configAll is changed) or (configEsMaster is changed)
