- block:
    - name: checking command 'curator'
      command: curator --version
      changed_when: false
  rescue:
    - include_tasks: 'install.yml target={{ item }}'
      become: yes
      with_items:
        - setuptools-38.5.2
        - certifi-2018.1.18
        - click-6.7
        - PyYAML-3.12
        - voluptuous-0.11.1
        - urllib3-1.22
        - elasticsearch-6.1.1
        - elasticsearch-curator-5.4.1
    - name: creating curator config file
      block:
        - file:
            path: '{{ ansible_user_dir }}/.curator'
            state: directory
        - template:
            src: 'curator.yml.j2'
            dest: '{{ ansible_user_dir }}/.curator/curator.yml'
        - command: curator_cli show_indices
          changed_when: false

- include_tasks: 'action_files.yml target={{ item }}'
  with_items:
    - hot_to_warm

- include_tasks: 'cron.yml target={{ item }}'
  with_items:
    - hot_to_warm
