- include_tasks: download.yml format='deb'

- name: "uploading {{ target }}-{{ elk_version }}-amd64.deb"
  copy:
    src: "downloaded_files/{{ target }}-{{ elk_version }}-amd64.deb"
    dest: "/tmp/{{ target }}-{{ elk_version }}-amd64.deb"

- block:
    - name: 'installing {{ target }}-{{ elk_version }}-amd64.deb'
      apt:
        deb: '/tmp/{{ target }}-{{ elk_version }}-amd64.deb'
  rescue:
    - command: "dpkg -i /tmp/{{ target }}-{{ elk_version }}-amd64.deb"
