- name: 'Updating filebeat.yml'
  template:
    src: 'filebeat.yml.j2'
    dest: '/etc/filebeat/filebeat.yml'
    mode: 0600

- name: Enable filebeat modules
  command: "filebeat modules enable {{ item }}"
  with_items:
    - system
    - auditd
    - '{{ filebeat_modules }}'
  register: moduleSt

- name: 'Testing filebeat'
  command: 'filebeat test {{ item }}'
  with_items:
    - output
    - config
  notify: Restart filebeat service
