- block:
    - name: "Checking {{ target }}"
      shell: "{{ target }} version"
      changed_when: false
      register: verChk
      failed_when: 'elk_version not in verChk.stdout'
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'

- include_tasks: '{{ target }}_templates.yml'
  tags: beats.config
