- name: 'Updating metricbeat.yml'
  template:
    src: 'metricbeat.yml.j2'
    dest: '/etc/metricbeat/metricbeat.yml'
    mode: 0600
  register: configSt

- name: Enable metricbeat modules
  command: "metricbeat modules enable {{ item }}"
  when: "item in group_names"
  with_items:
    - logstash
    - kibana
    - elasticsearch
  register: moduleSt

- name: 'Testing metricbeat'
  command: 'metricbeat test {{ item }}'
  with_items:
    - output
    - config
  notify: Restart metricbeat service
  when: configSt.changed or moduleSt.changed
