- name: 'Updating metricbeat.yml'
  template:
    src: 'metricbeat.yml.j2'
    dest: '/etc/metricbeat/metricbeat.yml'
    mode: 0600
  register: configSt

- name: Enable metricbeat modules
  template:
    src: "metricbeat_{{ item }}.yml.j2"
    dest: "/etc/metricbeat/modules.d/{{ item }}.yml"
  when: "item in group_names"
  notify: Restart metricbeat service
  with_items:
    - redis
    - kibana
    - elasticsearch

- name: 'Testing metricbeat'
  command: 'metricbeat test {{ item }}'
  with_items:
    - output
    - config
  notify: Restart metricbeat service
  when: configSt is changed

# - name: setup alias
#   uri:
#     url: http://elastic-ingest.service.consul:9200/metricbeat-*/_alias/active-logs
#     method: PUT
