- name: 'Updating packetbeat.yml'
  template:
    src: 'packetbeat.yml.j2'
    dest: '/etc/packetbeat/packetbeat.yml'
    mode: 0600
  register: configSt

- name: 'Testing packetbeat'
  command: 'packetbeat test {{ item }}'
  with_items:
    - output
    - modules
    - config
  when: configSt.changed
  changed_when: false
  notify: Restart packetbeat service
