- include_tasks: download.yml format=rpm

- name: "uploading {{ target }}-{{ elk_version }}-x86_64.rpm"
  copy:
    src: "downloaded_files/{{ target }}-{{ elk_version }}-x86_64.rpm"
    dest: "/tmp/{{ target }}-{{ elk_version }}-x86_64.rpm"
- name: "installing {{ target }}-{{ elk_version }}-x86_64.rpm"
  yum:
    name: "/tmp/{{ target }}-{{ elk_version }}-x86_64.rpm"
