- block:
    - name: "uploading {{ target }}-{{ elk_version }}-x86_64.rpm(上传中...)"
      copy:
        src: "downloaded_files/{{ target }}-{{ elk_version }}-x86_64.rpm"
        dest: "/tmp/{{ target }}-{{ elk_version }}-x86_64.rpm"
    - name: "installing {{ target }}-{{ elk_version }}-x86_64.rpm(安装中...)"
      yum:
        name: "/tmp/{{ target }}-{{ elk_version }}-x86_64.rpm"
  rescue:
    - name: "downloading {{ target }}-{{ elk_version }}-x86_64.rpm(下载中...)"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/{{ target }}/{{ target }}-{{ elk_version }}-x86_64.rpm"
        dest: "downloaded_files/"
      register: download
      until: download|succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: true
    - include_tasks: RedHat.yml
