- block:
    - name: 'checking logstash-{{ elk_version }}.deb file'
      stat:
        path: "roles/deploy.Logstash/files/logstash-{{ elk_version }}.deb"
        get_attributes: no
        get_checksum: no
        get_md5: no
        get_mime: no
      register: fileSt
      failed_when: not fileSt.stat.exists
      delegate_to: localhost
      become: no
      run_once: yes
  rescue:
    - name: 'downloading logstash-{{ elk_version }}.deb'
      get_url:
        url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ elk_version }}.deb"
        dest: "roles/deploy.Logstash/files/logstash-{{ elk_version }}.deb"
      delegate_to: localhost
      become: no
      run_once: yes

- name: 'uploading logstash-{{ elk_version }}.deb'
  copy:
    src: 'logstash-{{ elk_version }}.deb'
    dest: /tmp/

- name: 'installing logstash-{{ elk_version }}.deb'
  apt:
    deb: '/tmp/logstash-{{ elk_version }}.deb'
