- block:
    - name: 'uploading logstash-{{ elk_version }}.deb'
      copy:
        src: 'downloaded_files/logstash-{{ elk_version }}.deb'
        dest: /tmp/
    - name: 'installing logstash-{{ elk_version }}.deb'
      apt:
        deb: '/tmp/logstash-{{ elk_version }}.deb'
  rescue:
    - name: 'downloading logstash-{{ elk_version }}.deb'
      get_url:
        url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ elk_version }}.deb"
        dest: "downloaded_files/logstash-{{ elk_version }}.deb"
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: '{{ ansible_os_family }}.yml'

# - include_tasks: "plugins.yml target={{ target }}"
#   with_items:
#     - logstash-output-xmpp
#   loop_control:
#     loop_var: target
