- block:
    - name: Checking logstash
      shell: /usr/share/logstash/bin/logstash -V | awk '{ print $2 }'
      changed_when: false
      register: verChk
      failed_when: elk_version > verChk.stdout
  rescue:
    - include_tasks: env_check.yml
      when: verChk.rc == 1
    - include_tasks: '{{ ansible_os_family }}.yml'

- name: updating logstash configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/logstash/{{ item }}'
  with_items:
    - jvm.options
    - logstash.yml
  notify: Restart logstash service

- name: updating piplines
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item }}.conf'
  with_items:
    - 000-input
    - 999-output
  notify: Restart logstash service
