- block:
    - name: checking command 'logstash'
      command: '/usr/share/logstash/bin/logstash -V'
      changed_when: false
  rescue:
    - include_tasks: env_check.yml
    - include_tasks: '{{ ansible_os_family }}.yml'

- include_tasks: net_check.yml
  when: "logstash_beats_port != logstash_new_beats_port"

- name: updating logstash configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/logstash/{{ item }}'
  with_items:
    - jvm.options
    - logstash.yml
  notify: Restart logstash service

- name: updating piplines
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item }}.conf'
  with_items:
    - 000-input
    - 999-output
  notify: Restart logstash service
