- block:
    - name: 'uploading logstash-{{ elk_version }}.rpm'
      copy:
        src: 'downloaded_files/logstash-{{ elk_version }}.rpm'
        dest: /tmp/
    - name: 'installing logstash-{{ elk_version }}.rpm'
      yum:
        name: '/tmp/logstash-{{ elk_version }}.rpm'
  rescue:
    - include_tasks: download.yml format=rpm
    - include_tasks: '{{ ansible_os_family }}.yml'
