- block:
    - name: checking python2
      raw: test -e /usr/bin/python
      changed_when: false
      when: ansible_python_interpreter is not defined
  rescue:
    - name: checking python3
      raw: test -e /usr/bin/python3
      changed_when: false
    - name: add host into group 'ubuntu_hosts'
      block:
        - lineinfile:
            path: hosts.ini
            line: '{{ inventory_hostname }} ansible_python_interpreter=/usr/bin/python3'
            insertafter: '\[ubuntu_hosts\]'
            state: present
          delegate_to: localhost
          become: no
    - meta: clear_host_errors
    - meta: refresh_inventory

- block:
    - name: checking python3
      raw: test -e /usr/bin/python3
      changed_when: false
      when: ansible_python_interpreter is defined
  rescue:
    - name: checking python2
      raw: test -e /usr/bin/python
      changed_when: false
    - name: remove host from group 'ubuntu_hosts'
      lineinfile:
        path: hosts.ini
        line: '{{ inventory_hostname }} ansible_python_interpreter=/usr/bin/python3'
        state: absent
      delegate_to: localhost
      become: no
    - meta: clear_host_errors
    - meta: refresh_inventory
