- fail:
    msg: "At least 3 hosts needed in group '{{ item }}'"
  when: (groups[item] | length) < 3
  with_items:
    - elasticMasterNode
    - elasticHotNode

- fail:
    msg: "At least 1 host needed in group '{{ item }}'"
  when: (groups[item] | length) < 1
  with_items:
    - elasticWarmNode
    - logstash
    - kibana
