- block:
    - name: testing python2
      raw: test -e /usr/bin/python
      changed_when: false
      when: ansible_python_interpreter is not defined
  rescue:
    - name: testing python3
      raw: test -e /usr/bin/python3
      changed_when: false
    - name: set python3 as default python command
      lineinfile:
        path: hosts
        line: '{{ inventory_hostname }} ansible_python_interpreter=/usr/bin/python3'
        insertafter: '\[ubuntu_hosts\]'
        state: present
      delegate_to: localhost
      become: no
    - meta: clear_host_errors
    - meta: refresh_inventory
