- name: setup dns server
  lineinfile:
    path: "/etc/resolvconf/resolv.conf.d/head"
    line: "{{ item }}"
  with_items:
    - "nameserver 127.0.0.1"
    - "nameserver 1.1.1.1"

- name: restarting resolvconf service
  service:
    name: resolvconf
    state: restarted
