- include_tasks: check_groups.yml
  when: check_groups is defined and check_groups == true
  run_once: yes
- include_tasks: system.yml
- include_tasks: hostname.yml

- block:
    - name: checking java command
      command: /usr/bin/java -version
      changed_when: false
  rescue:
    - include_tasks: jre.yml
