- name: disable firewalld and selinux
  block:
    - service:
        name: firewalld
        state: stopped
        enabled: no
    - selinux:
        state: disabled
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version >= '7'"

- name: disable NetworkManager service
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: setup dns server
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ bond_interface }}"
    line: "{{ item }}"
  with_items:
    - "DNS1=127.0.0.1"
    - "DNS2=1.1.1.1"

- name: enable network service
  service:
    name: network
    state: restarted
    enabled: yes
