- name: 设置 sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    - {name: vm.max_map_count, value: 262144}
    - {name: vm.swappiness, value: 1}
    - {name: fs.file-max, value: 65536}
    - {name: net.ipv4.ip_forward, value: 1}

- name: 设置 limit.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: '{{ item }}'
  with_items:
    - 'elastic soft memlock unlimited'
    - 'elastic hard memlock unlimited'
    - 'elastic - nofile 65536'
    - 'ulimit -n 65536'
    - 'fsize unlimited'

- name: "Setup timezone(设置时区为 {{ timezone }})"
  timezone:
    name: '{{ timezone }}'

- name: 禁止 firewalld 服务
  service:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version >= '7'"
