- name: Setup sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    - {name: vm.max_map_count, value: 262144}
    - {name: vm.swappiness, value: 1}
    - {name: fs.file-max, value: 65536}
    - {name: net.ipv4.ip_forward, value: 1}

- name: Disable swap
  command: swapoff -a

- name: Config limit.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: '{{ item }}'
  with_items:
    - 'elasticsearch soft memlock unlimited'
    - 'elasticsearch hard memlock unlimited'
    - 'elasticsearch - nofile 65536'
    - 'ulimit -n 65536'
    - 'fsize unlimited'

- name: "Setup timezone to {{ timezone }}"
  timezone:
    name: '{{ timezone }}'

- name: Disable firewalld and selinux
  block:
    - service:
        name: firewalld
        state: stopped
        enabled: no
    - selinux:
        state: disabled
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version >= '7'"
