- block:
    - name: 'uploading kibana-{{ elk_version }}-amd64.deb'
      copy:
        src: 'downloaded_files/kibana-{{ elk_version }}-amd64.deb'
        dest: /tmp/
    - name: 'installing kibana-{{ elk_version }}-amd64.deb'
      apt:
        deb: '/tmp/kibana-{{ elk_version }}-amd64.deb'
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: create /var/run/kibana
      file:
        path: /var/run/kibana
        state: directory
        owner: kibana
        group: kibana
