- block:
    - name: checking command 'kibana'
      command: "/usr/share/kibana/bin/kibana -V"
      changed_when: false
      register: verChk
      failed_when: "elk_version > verChk.stdout"
    - name: checking kibana service status
      wait_for:
        port: '{{ kibana_port }}'
        timeout: 10
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'

- name: update kibana configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/kibana/{{ item }}'
  with_items:
    - kibana.yml
  notify: Restart kibana service

- include_role:
    name: deploy.ElasticSearch
