- name: 'cheking if port {{ kibana_port }} available'
  wait_for:
    host: '{{ item }}'
    port: '{{ kibana_new_port }}'
    state: stopped
    timeout: 3
  with_items:
    - 127.0.0.1
    - '{{ ansible_all_ipv4_addresses }}'
  register: portSt

- name: 'writing port number into group_vars/all.yml'
  run_once: true
  lineinfile:
    path: group_vars/all.yml
    regexp: '^kibana_port'
    line: "kibana_port: '{{ kibana_new_port }}'"
  when: portSt|succeeded
  delegate_to: localhost
  become: no
