- block:
    - name: 'uploading kibana-{{ elk_version }}-x86_64.rpm'
      copy:
        src: 'downloaded_files/kibana-{{ elk_version }}-x86_64.rpm'
        dest: /tmp/
    - name: 'installing kibana-{{ elk_version }}-x86_64.rpm'
      yum:
        name: '/tmp/kibana-{{ elk_version }}-x86_64.rpm'
        state: present
  rescue:
    - name: 'downloading kibana-{{ elk_version }}-x86_64.rpm'
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_version }}-x86_64.rpm"
        dest: "downloaded_files/kibana-{{ elk_version }}-x86_64.rpm"
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: '{{ ansible_os_family }}.yml'
