- block:
    - name: Checking haproxy command
      command: haproxy -v
      changed_when: false
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'
      notify: Enable haproxy service

- block:
    - name: Updating haproxy configure
      template:
        src: '{{ item }}.j2'
        dest: '/etc/haproxy/{{ item }}'
        backup: yes
      with_items:
        - haproxy.cfg
      register: updateSt
    - name: Checking haproxy configure
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      notify: Reloading haproxy configure
      when: updateSt.changed
  rescue:
    - name: Revert configure file
      shell: '{{ item }}'
      with_items:
        - rm /etc/haproxy/haproxy.cfg
        - mv -f $(ls -t /etc/haproxy/haproxy.cfg* | head -n 1) /etc/haproxy/haproxy.cfg
  always:
    - name: Keep the last 5 backup
      shell: "ls -1tr /etc/haproxy/haproxy.cfg* | head -n -5 | xargs -d '\n' rm -f --"
